### PR TITLE
update + remove hypercore/localcast support (closes #9)

### LINKED ISSUE #9: No peers
I'm using dat 13.8.2 and just installed hyperhealth globally.

I've got 2-3 peers on the same archive, but hyperhealth shows 0 peers. Could it be because some dependencies are too old?

### PR DESCRIPTION
**Pull request by joehand**
I'm trying to use this with the new dat-js and its mostly working! (some unrelated issues with connections). The CLI is also updated and works!?

* Removed hypercore support (because too confusing)
* Updated api to reflect current hyperdrive
* Removed localcast
* Added dat-link-resolve

This is a **major** update.

### CODE REVIEW

**Comment by okdistribute** [comment]
@joehand i think its important to keep hypercore support!

**Comment by okdistribute** [comment]
I reverted this merge

**Comment by joehand** [comment]
@karissa it currently doesn't work at all =(

I can put the time into adding hypercore support back in but thought it'd be better to have something that works for at least hyperdrive.

**Comment by okdistribute** [comment]
We need this for hypercore too! I think the code for checking if it's a hypercore or hyperdrive is OK, useful to perhaps have that in a separate module?

**Pull request merged**
